# Generated by Django 4.2.6 on 2024-08-09 10:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('link_precedence', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('linked_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_contacts', to='identity.contact')),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='identity_co_email_41ef35_idx'), models.Index(fields=['phone_number'], name='identity_co_phone_n_d83a4a_idx'), models.Index(fields=['email', 'phone_number'], name='identity_co_email_f98eda_idx')],
            },
        ),
    ]
