name: Multi-Environment CI/CD Pipeline

# Trigger only via manual dispatch, but allow branch filtering
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to (dev, stage, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod
    # Restrict workflow to specific branches
    branches:
      - dev        # For dev environment
      - stage      # For stage environment
      - prod       # For prod environment

jobs:
  selective-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set Environment Variables Based on User Input
      - name: Set Environment Variables
        run: echo "hello world"
