name: Multi-Environment CI/CD Pipeline

# Trigger only via manual dispatch
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to (dev, stage, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  selective-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Output
      - name: Set Environment Variables
        run: echo "hello world"
