name: Multi-Environment CI/CD Pipeline

# Trigger on push and manual dispatch
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy to (dev,prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      branch:
        description: "Select the branch to deploy from (dev,main)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - master

jobs:
  selective-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set Environment Variables Based on User Input
      - name: Set Environment Variables
        run: echo "hello world"
